### ISSUE TITLE
Add CHANGELOG and detailed migration notes to docs/meta/changelog

### ISSUE THREAD

**Issue by numberoverzero** [numberoverzero/bloop#76]
Blocks #75, once those docs are merged, the default docs page for Bloop will describe a 1.0.0 which is significantly different from 0.9.x.

To complete:

- [x] Document 0.9.x changes
  - [x] Find the first commit with each 0.9.x version
  - [x] Define the interface of the immediately previous commit for each
  - [x] Describe the delta
  - [x] Apply http://keepachangelog.com/en/0.3.0/
  - [x] include CHANGELOG in MANIFEST.in, README, docs/meta/changelog#Compact
- [x] Detailed migration guide
  - [x] docs/meta/changelog#Detailed
  - [x] Copy headings from Compact changelog
  - [x] Add old/new samples for each change
  - [x] Describe fixed exceptions, or new exceptions with existing code
- [x] Add "Unreleased" section to Compact, outlining #55, #71

**Comment by numberoverzero** [comment]
Commits for each version's release.  Next step: `git diff 0.9.x 0.9.x+1` for `x [0, 12]`

* 0.9.13 8c98c06241c4545cb2d101207ac386085008509a
* 0.9.12 f4dbefd3743b97d15bc46f6b90c00b261911e274
* 0.9.11 d5311be65dc5ed04d4f26dad0ad5d8accb295340
* 0.9.10 f36d24220e8666ab16f5913d138c0a3d8d1c6eed
* 0.9.9 632776c620d7e239cf1c0d4bc2e336e06cadbecc
* 0.9.8 d1363873e726eb4bdeb5beb76442318134144386
* 0.9.7 d4be1e334764a42193de07843132437a78cf9da8
* 0.9.6 819bddcd0ba0b0d6c28ee4aa758bb25ec889b6da
* 0.9.5 0ae24188fbef15cb26d3b55e402dadeb869b312d
* 0.9.4 3e1cff0a740ea3b93d751dc0d065be9aa9485ea3
* 0.9.3 fe6849fdc87139026889ec1e2894f9de3247a042
* 0.9.2 a083c0362bdbbc2447a7737c479f1e2d50e78634
* 0.9.1 4f085a622b4c4e2cb577b4dce243719148c85c7e
* 0.9.0 4f623bab95827018f4a2db5211595c3540ce8660

**Comment by numberoverzero** [comment]
Headings from Keep a Changelog, always in this order:

* `[Added]` for new features.
* `[Changed]` for changes in existing functionality.
* `[Deprecated]` for once-stable features removed in upcoming releases.
* `[Removed]` for deprecated features removed in this release.
* `[Fixed]` for any bug fixes.
* `[Security]` to invite users to upgrade in case of vulnerabilities.

**Comment by numberoverzero** [comment]
`git diff v0.9.0..v0.9.1` had no public changes.  Dropping 0.9.0 from the changelog since the upgrade instructions will be the same as 0.9.1.

**Comment by numberoverzero** [comment]
```
$ git log v0.9.13..docs-rewrite-03 --oneline | wc -l
560
```
